### ISSUE TITLE
Commands [Insert] and [Update]

### ISSUE THREAD

**Issue by Staed** [WuhanMonkey/UDPServerClient#3]
Given the wording in the requirements as well as later required 
functionality it seems that these commands only execute locally instead of
globally as it is currently done. Can you confirm this, so I can go ahead on
the change?

**Comment by WuhanMonkey** [comment]
First of all, I have already changed the Send part of the UDP server. But I haven't push it. For, 'delay', 'search' and 'show-all'. I think they should processed locally. 'get', 'insert', 'update' and 'delete' should be broadcast.

**Comment by WuhanMonkey** [comment]
oh, the search might be broadcasted too.

**Comment by Staed** [comment]
This has all been done.
**delay** is locally processed. 
**show-all** and **search** is broadcasted but locally processed.

**get**, **insert**, **update**, and **delete** is broadcast

Closing.
