### ISSUE TITLE
Create an Ack for RW commands in Model 3&4

### ISSUE THREAD

**Issue by Staed** [WuhanMonkey/UDPServerClient#5]
We will probably have to amend the **heldAcks** dict to include the 
command that was issued. Since _Python_ keys can use tuples as keys
because tuples are immutable, we can change the keys to the following:
**heldAcks** key is [(command, key)]

This should have minimal change to the existing code.

From the Milestone:

For Model 3&4 (Eventual Consistency):
The client node does not receive the results of the Send operation until all
nodes have done the operation and ACKed the Central server. In this case
the central server is responsible for processing the Acks and determining
which is the correct response.

This is done by comparing timestamps.

**Comment by Staed** [comment]
**heldAcks** key is now [(command, key)]
What is missing is having the result be _print_ only after all Acks
received by the central_server

**Comment by WuhanMonkey** [comment]
"For Model 3&4 (Eventual Consistency):
The client node does not receive the results of the Send operation until all
nodes have done the operation and ACKed the Central server. In this case
the central server is responsible for processing the Acks and determining
which is the correct response."

What do you mean for Send operation here?

**Comment by WuhanMonkey** [comment]
Shouldn't that for Model 3 or 4, Central server only waits for the k (W=k) write_acks or read_acks from any replicas and response the requester node with the result?

**Comment by Staed** [comment]
'Send' is just the term I use for all operations that are broadcast to the central_server, since before we did file input this was the way prefix attached to those messages.

My interpretation was that it was a writer-reader block, but you makes more sense. Can you confirm?

**Comment by WuhanMonkey** [comment]
Please see the issue I raised this afternoon.

**Comment by WuhanMonkey** [comment]
Hey, I will be late for a few minutes

On Thursday, March 12, 2015, Kelsey Yuen notifications@github.com wrote:

> 'Send' is just the term I use for all operations that are broadcast to the
> central_server, since before we did file input this was the way prefix
> attached to those messages.
> 
> My interpretation was that it was a writer-reader block, but you makes
> more sense. Can you confirm?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WuhanMonkey/UDPServerClient/issues/5#issuecomment-78749958
> .

## 

_Chengpeng(Chester) Hu_

_University of Illinois-Urbana Champaign_

Major in Computer Engineering | Department of Electrical and Computer
Engineering

Research Assistant in Liu Nanobionics Lab

_hu43@illinois.edu hu43@illinois.edu_
